"""
Django settings for hello_django project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dca=%ylp(8xum#$tju&+rq3&019=4z4@y$t29p==537$$u90kx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [u"192.168.56.102"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hello_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hello_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {                                                                                                                                                                                                                    
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test',  # Or path to database file if using sqlite3.
        'USER': 'sdk',  # Not used with sqlite3.
        'PASSWORD': 'sdk',  # Not used with sqlite3.
        'HOST': '127.0.0.1',  # Set to sempty string for localhost. Not used with sqlite3.
        'PORT': '19816',  # Set to empty string for default. Not used with sqlite3.
        # 'CONN_MAX_AGE': 1*24*60*60,
        'OPTIONS': {
            'init_command': 'SET storage_engine=INNODB,  SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED, autocommit=1, names "utf8";',
        },
    }
}

# Logging
# https://docs.djangoproject.com/en/1.10/ref/settings/#logging
# https://docs.djangoproject.com/en/1.10/topics/logging/

LOGGING = {
    'version':1,
    'disable_existing_loggers': False,
    'formatters':{
        'verbose':{
            'format':'%(levelname)s %(asctime)s %(module)s %(lineno)d %(process)d %(thread)d %(message)s',
            'datefmt':"%Y-%m-%d %H:%M:%S"
        },
        'simple':{
            'format':'%(message)s'
        }
    },
    'handlers':{
        'console':{
            'class':'logging.StreamHandler',
            'formatter':'verbose'
        },
        'file_statistics':{
            'level':'INFO',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'formatter':'simple',
            'filename':'/home/nieyong/temp/logs/file_statistics.log',
            'when':'D',
            'backupCount':15
        },
        'file_sysinfo':{
            'level':'INFO',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'formatter':'verbose',
            'filename':'/home/nieyong/temp/logs/file_sysinfo.log',
            'when':'H',
            'backupCount':24
        }
    },
    'loggers':{
        'django':{
            'level':'INFO',
            'handlers':['console', 'file_sysinfo']
        },
        'stats':{
            'level':'INFO',
            'handlers':['file_statistics']
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
